### ISSUE TITLE
Implement Quine in Python

### ISSUE THREAD

**Issue by thevirtualbuddy** [craplab/WeirdScripts#13]

**Comment by mmdbalkhi** [comment]
Hi, I can do it!

**Comment by thevirtualbuddy** [comment]
Sure @mmdbalkhi , Quine program are those programs which print itself i.e. its own source code is the output. And yes, this repository welcomes such programs which explains/demonstrates the lesser known features of any programming language ..

**Comment by thevirtualbuddy** [comment]
Shall I assign you for this issue? @mmdbalkhi

**Comment by mmdbalkhi** [comment]
If you want, yes, why not!

**Comment by thevirtualbuddy** [comment]
Go ahead @mmdbalkhi

**Comment by thevirtualbuddy** [comment]
That was not Quine Program @mmdbalkhi as I mentioned "Quine program are those programs which print itself i.e. its own source code is the output."
I am merging your code but this issue remains open as the program doesn't fulfill the requirement for this issue.

**Comment by mmdbalkhi** [comment]
> That was not Quine Program @mmdbalkhi as I mentioned "Quine program are those programs which print itself i.e. its own source code is the output." I am merging your code but this issue remains open as the program doesn't fulfill the requirement for this issue.

I'm sorry I was wrong. Because I asked you above about lesser known capabilities. I'm trying to find something really weird.

**Comment by thevirtualbuddy** [comment]
No worries :)

**Comment by thevirtualbuddy** [comment]
Above PR is a self printing program but can't be called Quine. Issue remains open.
