### ISSUE TITLE
Bash script to rename files randomly 

### ISSUE THREAD

**Issue by thevirtualbuddy** [craplab/WeirdScripts#16]

**Comment by aditirao7** [comment]
Hi, can you please elaborate? Should every file in a directory be renamed?

**Comment by thevirtualbuddy** [comment]
Not required @aditirao7, the script can accept arguments as the filenames(either space separated or comma separated), and those files can be renamed randomly, that is enough

**Comment by aditirao7** [comment]
So by rename randomly do you mean it should generate a random name for each file? Also, can I work on this?

**Comment by thevirtualbuddy** [comment]
yes, random name for each file (use a dictionary of words maybe and select words randomly). Sure, assigning you
