### ISSUE TITLE
Implement Quine in HTML

### ISSUE THREAD

**Issue by thevirtualbuddy** [craplab/WeirdScripts#3]
The HTML code should display its own source code in the browser.

**Comment by aditirao7** [comment]
Can a script or style tag be used or should it be pure HTML? Can I be assigned?

**Comment by thevirtualbuddy** [comment]
Sure @aditirao7 go ahead please 👍

**Comment by thevirtualbuddy** [comment]
Style and script tag can be used. But the style and script tag should be printed too then. @aditirao7
