### ISSUE TITLE
Implement python script to automate commit on GitHub for 365 days

### ISSUE THREAD

**Issue by thevirtualbuddy** [craplab/WeirdScripts#53]
The script should make changes in a text file and should make commit everyday for next 365 days 👯 
![image](https://user-images.githubusercontent.com/42694653/136329415-9da46c2b-9adf-4709-b173-e98b03b8ce29.png)

Take motivation and help from this awesome post:
https://bugsyteam-en.blogspot.com/2021/10/git-contribution-graph-green.html

PS: This script should not be used to deceive people they contribute everyday.

**Comment by AmirNaghibi** [comment]
@thevirtualbuddy  could you assign this to me?
