### ISSUE TITLE
Implement Python script to search random videos on YouTube

### ISSUE THREAD

**Issue by thevirtualbuddy** [craplab/WeirdScripts#62]
The script should be able to search random videos on YouTube which should be logged with a person's gmail id. The motive of the script is to break the bubble that the YouTube algorithm forms for any individual. 

Here, bubble refers to the YouTube feeding similar type of content to the user based on his search and watch history.

**Comment by BobinMathew** [comment]
So I have to give my youtube credentials along with with the search keyword in python?
