### ISSUE TITLE
Improve PR Review Process

### ISSUE THREAD

**Issue by AmirNaghibi** [craplab/WeirdScripts#66]
I've noticed some PRs don't meet the requirements such as having a README.md or being in the correct directory. So we have to remind them everytime they don't meet the requirements.

We can improve this situation by installing a Github App called **[Pull Request Checklist Buddy](https://github.com/marketplace/pull-request-checklist-buddy)**. 

Then we can add a file called **PRCHECKLIST** to specify and remind what users need to do. Users will see the checklist after they create their PR.

<img width="980" alt="Screen Shot 2021-10-13 at 2 23 14 PM" src="https://user-images.githubusercontent.com/20001191/137214458-e7e13f9c-fcdf-40a3-be93-79141fea6935.png">

Here is [documentation](https://mibexsoftware.atlassian.net/wiki/spaces/CB/pages/2936144097/Getting+started).

@thevirtualbuddy I can create the **PRCHECKLIST** and all you need to do is add the app and enable it to access this repository.

**Comment by thevirtualbuddy** [comment]
Sure @AmirNaghibi 
Please proceed with it.

**Comment by thevirtualbuddy** [comment]
![Web capture_14-10-2021_11020_github com](https://user-images.githubusercontent.com/42694653/137257480-b54ccb78-974f-4f8b-b43d-b770025643df.jpeg)
